In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import math

In [83]:
def getIndusText(index):
    URL = "https://www.indus.epigraphica.de/icitview.php"
    page = requests.post(URL, auth=('icit', 'seal123'), data ={'idicit': str(index)})
    soup = BeautifulSoup(page.content, "html.parser")
    results = soup.find_all("table")
    try:
        if(len(results) > 1):
            enc = pd.read_html(results[1].prettify())[0]
            if 'text' in enc.columns:
                enc = enc.dropna(subset=['text'])
                return enc
            return pd.DataFrame()
    except ValueError:
        print("Got Value Error in ", index)
        return pd.DataFrame()
    return pd.DataFrame()

In [71]:
# results = soup.find_all("table")
# print(len(results))
# #print(results[1].prettify())
# from IPython.display import HTML
# display(HTML("".join(results[1].prettify())))
# print(2)
# display(HTML("".join(results[2].prettify())))
# print(3)
# display(HTML("".join(results[3].prettify())))

In [72]:
getIndusText(300)

,class,lines,direction,text,signs,complete,alignment,sign height,images
1,PP,1,R/L,+740-048-741-851+,4,Y,NaN,NaN,NaN
3,UC,1,R/L,+700-033-711-335-575-413+,6,Y,NaN,NaN,NaN

In [85]:
df = pd.DataFrame()
start = 4500
end = 5000
for i in range(start,end):
    print(i)
    df = df.append(getIndusText(i))
filename = f'extracted_script_{start}-{end}.csv'
df.to_csv(filename)
df

4500
Got Value Error in  4500
4501
Got Value Error in  4501
4502
Got Value Error in  4502
4503
Got Value Error in  4503
4504
Got Value Error in  4504
4505
Got Value Error in  4505
4506
4507
Got Value Error in  4507
4508
4509
Got Value Error in  4509
4510
4511
4512
4513
4514
4515
4516
4517
4518
4519
Got Value Error in  4519
4520
4521
4522
4523
Got Value Error in  4523
4524
Got Value Error in  4524
4525
Got Value Error in  4525
4526
Got Value Error in  4526
4527
Got Value Error in  4527
4528
Got Value Error in  4528
4529
Got Value Error in  4529
4530
Got Value Error in  4530
4531
Got Value Error in  4531
4532
Got Value Error in  4532
4533
Got Value Error in  4533
4534
Got Value Error in  4534
4535
Got Value Error in  4535
4536
Got Value Error in  4536
4537
Got Value Error in  4537
4538
Got Value Error in  4538
4539
Got Value Error in  4539
4540
4541
Got Value Error in  4541
4542
Got Value Error in  4542
4543
Got Value Error in  4543
4544
Got Value Error in  4544
4545
Got Value Error in  4545
4546
Got Value Error in  4546
4547
Got Value Error in  4547
4548
Got Value Error in  4548
4549
Got Value Error in  4549
4550
Got Value Error in  4550
4551
Got Value Error in  4551
4552
Got Value Error in  4552
4553
Got Value Error in  4553
4554
Got Value Error in  4554
4555
Got Value Error in  4555
4556
Got Value Error in  4556
4557
Got Value Error in  4557
4558
Got Value Error in  4558
4559
Got Value Error in  4559
4560
Got Value Error in  4560
4561
Got Value Error in  4561
4562
Got Value Error in  4562
4563
Got Value Error in  4563
4564
Got Value Error in  4564
4565
Got Value Error in  4565
4566
Got Value Error in  4566
4567
Got Value Error in  4567
4568
Got Value Error in  4568
4569
Got Value Error in  4569
4570
Got Value Error in  4570
4571
Got Value Error in  4571
4572
Got Value Error in  4572
4573
Got Value Error in  4573
4574
Got Value Error in  4574
4575
Got Value Error in  4575
4576
Got Value Error in  4576
4577
Got Value Error in  4577
4578
Got Value Error in  4578
4579
Got Value Error in  4579
4580
Got Value Error in  4580
4581
Got Value Error in  4581
4582
Got Value Error in  4582
4583
Got Value Error in  4583
4584
Got Value Error in  4584
4585
Got Value Error in  4585
4586
Got Value Error in  4586
4587
Got Value Error in  4587
4588
Got Value Error in  4588
4589
Got Value Error in  4589
4590
Got Value Error in  4590
4591
Got Value Error in  4591
4592
Got Value Error in  4592
4593
Got Value Error in  4593
4594
Got Value Error in  4594
4595
Got Value Error in  4595
4596
Got Value Error in  4596
4597
Got Value Error in  4597
4598
Got Value Error in  4598
4599
Got Value Error in  4599
4600
Got Value Error in  4600
4601
Got Value Error in  4601
4602
Got Value Error in  4602
4603
Got Value Error in  4603
4604
Got Value Error in  4604
4605
Got Value Error in  4605
4606
Got Value Error in  4606
4607
Got Value Error in  4607
4608
Got Value Error in  4608
4609
Got Value Error in  4609
4610
Got Value Error in  4610
4611
Got Value Error in  4611
4612
Got Value Error in  4612
4613
Got Value Error in  4613
4614
Got Value Error in  4614
4615
Got Value Error in  4615
4616
Got Value Error in  4616
4617
4618
4619
4620
4621
4622
4623
4624
4625
4626
4627
4628
4629
4630
4631
Got Value Error in  4631
4632
Got Value Error in  4632
4633
4634
4635
Got Value Error in  4635
4636
4637
Got Value Error in  4637
4638
Got Value Error in  4638
4639
4640
4641
4642
4643
4644
4645
4646
4647
4648
4649
4650
4651
4652
4653
Got Value Error in  4653
4654
Got Value Error in  4654
4655
4656
4657
4658
4659
4660
4661
4662
4663
Got Value Error in  4663
4664
Got Value Error in  4664
4665
Got Value Error in  4665
4666
Got Value Error in  4666
4667
4668
4669
Got Value Error in  4669
4670
Got Value Error in  4670
4671
4672
4673
Got Value Error in  4673
4674
Got Value Error in  4674
4675
Got Value Error in  4675
4676
Got Value Error in  4676
4677
4678
4679
4680
4681
4682
4683
4684
4685
Got Value Error in  4685
4686
4687
4688
Got Value Error in  4688
4689
4690
4691
Got Value Error in  4691
4692
4693
4694
Got Value Error in  4694
4695
4696
4697
Got Value Error in  4697
4698
4699
Got Value Error in  4699
4700
Got Value Error in  4700
4701
4702
4703
4704
Got Value Error in  4704
4705
Got Value Error in  4705
4706
Got Value Error in  4706
4707
Got Value Error in  4707
4708
Got Value Error in  4708
4709
Got Value Error in  4709
4710
Got Value Error in  4710
4711
4712
4713
4714
4715
4716
Got Value Error in  4716
4717
Got Value Error in  4717
4718
Got Value Error in  4718
4719
4720
Got Value Error in  4720
4721
Got Value Error in  4721
4722
Got Value Error in  4722
4723
4724
4725
4726
4727
4728
Got Value Error in  4728
4729
4730
4731
4732
4733
4734
4735
Got Value Error in  4735
4736
Got Value Error in  4736
4737
Got Value Error in  4737
4738
Got Value Error in  4738
4739
4740
4741
Got Value Error in  4741
4742
Got Value Error in  4742
4743
4744
Got Value Error in  4744
4745
Got Value Error in  4745
4746
Got Value Error in  4746
4747
Got Value Error in  4747
4748
4749
4750
4751
4752
Got Value Error in  4752
4753
4754
4755
Got Value Error in  4755
4756
4757
4758
4759
4760
4761
Got Value Error in  4761
4762
Got Value Error in  4762
4763
4764
4765
4766
4767
4768
4769
4770
4771
Got Value Error in  4771
4772
Got Value Error in  4772
4773
4774
4775
4776
4777
4778
Got Value Error in  4778
4779
4780
4781
4782
4783
4784
4785
4786
4787
4788
4789
4790
4791
4792
4793
4794
4795
4796
4797
Got Value Error in  4797
4798
4799
4800
4801
4802
Got Value Error in  4802
4803
4804
4805
4806
4807
4808
4809
4810
4811
4812
4813
4814
4815
Got Value Error in  4815
4816
Got Value Error in  4816
4817
Got Value Error in  4817
4818
Got Value Error in  4818
4819
Got Value Error in  4819
4820
Got Value Error in  4820
4821
Got Value Error in  4821
4822
4823
Got Value Error in  4823
4824
Got Value Error in  4824
4825
Got Value Error in  4825
4826
Got Value Error in  4826
4827
Got Value Error in  4827
4828
4829
Got Value Error in  4829
4830
Got Value Error in  4830
4831
Got Value Error in  4831
4832
Got Value Error in  4832
4833
Got Value Error in  4833
4834
Got Value Error in  4834
4835
Got Value Error in  4835
4836
Got Value Error in  4836
4837
4838
Got Value Error in  4838
4839
4840
Got Value Error in  4840
4841
Got Value Error in  4841
4842
Got Value Error in  4842
4843
Got Value Error in  4843
4844
Got Value Error in  4844
4845
Got Value Error in  4845
4846
4847
Got Value Error in  4847
4848
Got Value Error in  4848
4849
Got Value Error in  4849
4850
Got Value Error in  4850
4851
Got Value Error in  4851
4852
4853
4854
Got Value Error in  4854
4855
Got Value Error in  4855
4856
4857
Got Value Error in  4857
4858
Got Value Error in  4858
4859
Got Value Error in  4859
4860
Got Value Error in  4860
4861
4862
Got Value Error in  4862
4863
Got Value Error in  4863
4864
4865
Got Value Error in  4865
4866
4867
4868
4869
4870
4871
4872
4873
4874
Got Value Error in  4874
4875
4876
4877
4878
4879
4880
Got Value Error in  4880
4881
4882
4883
4884
4885
4886
Got Value Error in  4886
4887
4888
4889
4890
4891
4892
4893
4894
4895
4896
4897
4898
4899
4900
4901
4902
4903
4904
4905
4906
4907
4908
Got Value Error in  4908
4909
4910
4911
4912
4913
4914
4915
4916
4917
4918
Got Value Error in  4918
4919
4920
4921
4922
4923
4924
4925
4926
4927
4928
4929
4930
4931
4932
4933
4934
4935
4936
4937
4938
4939
4940
4941
4942
4943
4944
4945
4946
4947
Got Value Error in  4947
4948
4949
4950
4951
4952
4953
4954
4955
4956
4957
4958
4959
4960
4961
4962
4963
4964
4965
4966
4967
4968
4969
4970
4971
4972
4973
4974
4975
4976
4977
4978
4979
4980
4981
4982
4983
4984
4985
4986
4987
4988
4989
4990
4991
4992
4993
4994
4995
4996
4997
4998
Got Value Error in  4998
4999

,class,lines,direction,text,signs,complete,alignment,sign height,images
1,??,1,R/L,]000-176-000[,3,N,NaN,NaN,NaN
1,??,1,NaN,+110[,1,?,NaN,NaN,NaN
1,??,1,R/L,+111-003-250+,3,Y,Unordered,Unequal,NaN
1,??,1,NaN,]035-000[,2,N,NaN,NaN,NaN
1,NU,1,NaN,+031+,1,Y,Indefinable,Indefinable,NaN
1,UC,1,NaN,+156[,1,?,NaN,NaN,NaN
1,??,1,NaN,+034-000+,2,N,NaN,NaN,NaN

In [59]:
df

,class,lines,direction,text,signs,complete,alignment,sign height,images
1,UC,1,NaN,]405+,1,?,Indefinable,Indefinable,NaN
1,PP,1,R/L,+740-048-741-851+,4,Y,NaN,NaN,NaN
3,UC,1,R/L,+700-033-711-335-575-413+,6,Y,NaN,NaN,NaN
1,VN,1,R/L,+700-031[,2,?,NaN,NaN,NaN
3,UC,1,L/R,+400-740-000[,3,N,NaN,NaN,NaN
1,SC,1,R/L,]220-700[,2,?,NaN,NaN,NaN
3,UC,1,R/L,]740-840[,2,?,NaN,NaN,NaN
1,SP,1,R/L,+151-760-220-003-002-861+,6,Y,Stacked linear,Unequal,NaN
1,ZN,1,R/L,+255-033[,2,?,NaN,NaN,NaN
3,UC,1,R/L,+416-590-033[,3,?,NaN,NaN,NaN

In [60]:
df = getIndusText(276)

In [61]:
df

Empty DataFrame
Columns: []
Index: []

In [65]:
start = 1
end = 100
name = f'extracted_script_{start}-{end}.csv'
print(name)

extracted_script_1-100.csv